theme: jekyll-theme-midnight
title: Welcome to my homepage! This is Fawkes4494d3. :D
description: Feel free to bookmark this page to keep an eye on my updates.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
